DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS email_tokens;
DROP TABLE IF EXISTS refresh_tokens;
ALTER TABLE users 
DROP CONSTRAINT IF EXISTS fk_avatar;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;