// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/access_notifier.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/access_notifier.go -destination=test/mocks/mock_access_notifier.go -package=mocks -mock_names=Service=MockAccessNotifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	entity "task-trail/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessNotifier is a mock of AccessNotifier interface.
type MockAccessNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockAccessNotifierMockRecorder
	isgomock struct{}
}

// MockAccessNotifierMockRecorder is the mock recorder for MockAccessNotifier.
type MockAccessNotifierMockRecorder struct {
	mock *MockAccessNotifier
}

// NewMockAccessNotifier creates a new mock instance.
func NewMockAccessNotifier(ctrl *gomock.Controller) *MockAccessNotifier {
	mock := &MockAccessNotifier{ctrl: ctrl}
	mock.recorder = &MockAccessNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessNotifier) EXPECT() *MockAccessNotifierMockRecorder {
	return m.recorder
}

// SendAccountConfirmation mocks base method.
func (m *MockAccessNotifier) SendAccountConfirmation(email entity.Email, tokenID entity.ConfirmationTokenID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAccountConfirmation", email, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAccountConfirmation indicates an expected call of SendAccountConfirmation.
func (mr *MockAccessNotifierMockRecorder) SendAccountConfirmation(email, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccountConfirmation", reflect.TypeOf((*MockAccessNotifier)(nil).SendAccountConfirmation), email, tokenID)
}

// SendPasswordResetConfirmation mocks base method.
func (m *MockAccessNotifier) SendPasswordResetConfirmation(email entity.Email, tokenID entity.ConfirmationTokenID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetConfirmation", email, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetConfirmation indicates an expected call of SendPasswordResetConfirmation.
func (mr *MockAccessNotifierMockRecorder) SendPasswordResetConfirmation(email, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetConfirmation", reflect.TypeOf((*MockAccessNotifier)(nil).SendPasswordResetConfirmation), email, tokenID)
}
