// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/token/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/token/contracts.go -destination=test/mocks/mock_token.go -package=mocks -mock_names=Service=MockTokenService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dto "task-trail/internal/usecase/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of Service interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GenAccessToken mocks base method.
func (m *MockTokenService) GenAccessToken(userID int) (*dto.AccessTokenRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenAccessToken", userID)
	ret0, _ := ret[0].(*dto.AccessTokenRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenAccessToken indicates an expected call of GenAccessToken.
func (mr *MockTokenServiceMockRecorder) GenAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenAccessToken", reflect.TypeOf((*MockTokenService)(nil).GenAccessToken), userID)
}

// GenRefreshToken mocks base method.
func (m *MockTokenService) GenRefreshToken(userID int) (*dto.RefreshTokenRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenRefreshToken", userID)
	ret0, _ := ret[0].(*dto.RefreshTokenRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenRefreshToken indicates an expected call of GenRefreshToken.
func (mr *MockTokenServiceMockRecorder) GenRefreshToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenRefreshToken", reflect.TypeOf((*MockTokenService)(nil).GenRefreshToken), userID)
}

// VerifyAccessToken mocks base method.
func (m *MockTokenService) VerifyAccessToken(token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockTokenServiceMockRecorder) VerifyAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockTokenService)(nil).VerifyAccessToken), token)
}

// VerifyRefreshToken mocks base method.
func (m *MockTokenService) VerifyRefreshToken(token string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockTokenServiceMockRecorder) VerifyRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockTokenService)(nil).VerifyRefreshToken), token)
}
