// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/access_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/access_token.go -destination=test/mocks/mock_access_token.go -package=mocks -mock_names=Service=MockAccessTokenService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dto "task-trail/internal/application/dto"
	entity "task-trail/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessTokenService is a mock of AccessTokenService interface.
type MockAccessTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenServiceMockRecorder
	isgomock struct{}
}

// MockAccessTokenServiceMockRecorder is the mock recorder for MockAccessTokenService.
type MockAccessTokenServiceMockRecorder struct {
	mock *MockAccessTokenService
}

// NewMockAccessTokenService creates a new mock instance.
func NewMockAccessTokenService(ctrl *gomock.Controller) *MockAccessTokenService {
	mock := &MockAccessTokenService{ctrl: ctrl}
	mock.recorder = &MockAccessTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenService) EXPECT() *MockAccessTokenServiceMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockAccessTokenService) GenerateAccessToken(userID entity.UserID) (dto.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID)
	ret0, _ := ret[0].(dto.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockAccessTokenServiceMockRecorder) GenerateAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockAccessTokenService)(nil).GenerateAccessToken), userID)
}

// GenerateRefreshToken mocks base method.
func (m *MockAccessTokenService) GenerateRefreshToken(userID entity.UserID, jti *entity.RefreshToken) (dto.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID, jti)
	ret0, _ := ret[0].(dto.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockAccessTokenServiceMockRecorder) GenerateRefreshToken(userID, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockAccessTokenService)(nil).GenerateRefreshToken), userID, jti)
}

// GenerateTokensPair mocks base method.
func (m *MockAccessTokenService) GenerateTokensPair(userID entity.UserID, jti *entity.RefreshToken) (dto.AccessToken, dto.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokensPair", userID, jti)
	ret0, _ := ret[0].(dto.AccessToken)
	ret1, _ := ret[1].(dto.RefreshToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokensPair indicates an expected call of GenerateTokensPair.
func (mr *MockAccessTokenServiceMockRecorder) GenerateTokensPair(userID, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokensPair", reflect.TypeOf((*MockAccessTokenService)(nil).GenerateTokensPair), userID, jti)
}

// VerifyAccessToken mocks base method.
func (m *MockAccessTokenService) VerifyAccessToken(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockAccessTokenServiceMockRecorder) VerifyAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockAccessTokenService)(nil).VerifyAccessToken), token)
}

// VerifyRefreshToken mocks base method.
func (m *MockAccessTokenService) VerifyRefreshToken(token string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockAccessTokenServiceMockRecorder) VerifyRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockAccessTokenService)(nil).VerifyRefreshToken), token)
}
