// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/confirmation_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/confirmation_token.go -destination=test/mocks/mock_confirmation_token.go -package=mocks -mock_names=Service=MockConfirmationTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "task-trail/internal/domain/entity"
	repository "task-trail/internal/domain/repository"

	gomock "go.uber.org/mock/gomock"
)

// MockConfirmationTokenRepository is a mock of ConfirmationTokenRepository interface.
type MockConfirmationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockConfirmationTokenRepositoryMockRecorder is the mock recorder for MockConfirmationTokenRepository.
type MockConfirmationTokenRepositoryMockRecorder struct {
	mock *MockConfirmationTokenRepository
}

// NewMockConfirmationTokenRepository creates a new mock instance.
func NewMockConfirmationTokenRepository(ctrl *gomock.Controller) *MockConfirmationTokenRepository {
	mock := &MockConfirmationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockConfirmationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationTokenRepository) EXPECT() *MockConfirmationTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConfirmationTokenRepository) Create(ctx context.Context, arg1 *entity.ConfirmationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConfirmationTokenRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfirmationTokenRepository)(nil).Create), ctx, arg1)
}

// Find mocks base method.
func (m *MockConfirmationTokenRepository) Find(ctx context.Context, filter repository.ConfirmationTokenFilter) ([]*entity.ConfirmationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].([]*entity.ConfirmationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConfirmationTokenRepositoryMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConfirmationTokenRepository)(nil).Find), ctx, filter)
}

// GetByID mocks base method.
func (m *MockConfirmationTokenRepository) GetByID(ctx context.Context, tokenID entity.ConfirmationTokenID) (*entity.ConfirmationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tokenID)
	ret0, _ := ret[0].(*entity.ConfirmationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockConfirmationTokenRepositoryMockRecorder) GetByID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockConfirmationTokenRepository)(nil).GetByID), ctx, tokenID)
}

// Update mocks base method.
func (m *MockConfirmationTokenRepository) Update(ctx context.Context, enitity *entity.ConfirmationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, enitity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConfirmationTokenRepositoryMockRecorder) Update(ctx, enitity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfirmationTokenRepository)(nil).Update), ctx, enitity)
}
