definitions:
  request.EmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.ResetPasswordRequest:
    properties:
      password:
        maxLength: 50
        minLength: 8
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
  request.UpdateUser:
    properties:
      username:
        maxLength: 100
        type: string
    type: object
  request.User:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  request.VerifyRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  response.ErrAPI:
    properties:
      metadata:
        additionalProperties: {}
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: musaev.ae@hiraise.net
    name: HiRaise
    url: https://hiraise.net/
  license:
    name: MIT License
    url: https://mit-license.org/
  title: Task Trail API
  version: "1.0"
paths:
  /v1/auth/check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: authentication required
          schema:
            $ref: '#/definitions/response.ErrAPI'
      security:
      - BearerAuth: []
      summary: check user authentication
      tags:
      - /v1/auth
  /v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "401":
          description: invalid credentials
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: login user
      tags:
      - /v1/auth
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: authentication required
          schema:
            $ref: '#/definitions/response.ErrAPI'
      security:
      - BearerAuth: []
      summary: logout user
      tags:
      - /v1/auth
  /v1/auth/password/forgot:
    post:
      consumes:
      - application/json
      parameters:
      - description: user email
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: send reset password email
      tags:
      - /v1/auth
  /v1/auth/password/reset:
    post:
      consumes:
      - application/json
      parameters:
      - description: token and new password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: reset user password
      tags:
      - /v1/auth
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: refresh token is invalid
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: refresh tokens pair
      tags:
      - /v1/auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: endpoint for register new user
      parameters:
      - description: user email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "409":
          description: user already exists
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: register new user
      tags:
      - /v1/auth
  /v1/auth/resend-verification:
    post:
      consumes:
      - application/json
      parameters:
      - description: user email
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: resend account verification email
      tags:
      - /v1/auth
  /v1/auth/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: token is invalid
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "404":
          description: token or user not found
          schema:
            $ref: '#/definitions/response.ErrAPI'
      summary: verify user account
      tags:
      - /v1/auth
  /v1/users/{id}:
    get:
      consumes:
      - application/json
      description: '...'
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: return user by id
      tags:
      - /v1/users
  /v1/users/me:
    get:
      consumes:
      - application/json
      description: '...'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: return current user
      tags:
      - /v1/users
    patch:
      consumes:
      - application/json
      description: '...'
      parameters:
      - description: user data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "401":
          description: authentication required
          schema:
            $ref: '#/definitions/response.ErrAPI'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/response.ErrAPI'
      security:
      - BearerAuth: []
      summary: update current user
      tags:
      - /v1/users
  /v1/users/me/avatar:
    patch:
      consumes:
      - application/json
      description: '...'
      parameters:
      - description: new file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: authentication required
          schema:
            $ref: '#/definitions/response.ErrAPI'
      security:
      - BearerAuth: []
      summary: upload new avatar
      tags:
      - /v1/users
securityDefinitions:
  BearerAuth:
    in: cookie
    name: at
    type: apiKey
swagger: "2.0"
