definitions:
  customerrors.Http:
    properties:
      description:
        type: string
      metadata: {}
    type: object
  request.NewUser:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
info:
  contact:
    email: musaev.ae@hiraise.net
    name: HiRaise
    url: https://hiraise.net/
  license:
    name: MIT License
    url: https://mit-license.org/
  title: Task Trail API
  version: "1.0"
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: endpoint for create new user
      parameters:
      - description: user email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerrors.Http'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/customerrors.Http'
      summary: create new user
      tags:
      - /v1/users
swagger: "2.0"
