name: Delivery
on:
  workflow_dispatch:
    inputs:
      envType:
        type: choice
        description: 'Type of environment "dev" or "prod'
        default: 'dev'
        options:
          - dev
          - prod
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Log into registry ${{ env.REGISTRY }}"
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-img"
          tags: |
            type=raw,value=${{ inputs.envType }}
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: "${{ github.event_name != 'pull_request' }}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          build-args: |
            TOKEN=${{ secrets.TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment DEV stack hook
        if: ${{ inputs.envType == 'dev' }} 
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.DEV_WEBHOOK_URL }}
      - name: Invoke deployment PROD stack hook
        if: ${{ inputs.envType == 'prod' }} 
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.PROD_WEBHOOK_URL }}

