name: test

on:     
  pull_request:
    branches:           
      - '**'       

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 3m0s --verbose
    